/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Login
         * @description Authenticate by email + password. Issue HS256 JWT.
         *
         *     Uniform 401 on unknown user or wrong password (no existence leak).
         *     429 with Retry-After if 5 failed attempts in 15 minutes for this email.
         *     Audit row written on Success and on known-email Denied.
         */
        post: operations["post_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tier-config/{tier_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Tier Config
         * @description PATCH a tier_config row.
         *
         *     PO-only. Writes the full before / after snapshot to audit_trail_entries
         *     in the same transaction; if the audit write fails, the UPDATE rolls back.
         */
        patch: operations["patch_tier_config_api_v1_admin_tier_config__tier_number__patch"];
        trace?: never;
    };
    "/api/v1/admin/tier-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tier Config List
         * @description Read every escalation tier config. PO-only. Reads not audited.
         */
        get: operations["get_tier_config_list_api_v1_admin_tier_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/threshold-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Threshold Register List
         * @description Read every threshold calibration register row. PO-only. Reads not audited.
         */
        get: operations["get_threshold_register_list_api_v1_admin_threshold_register_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/threshold-register/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Threshold Register
         * @description PATCH a threshold_calibration_register row.
         *
         *     PO-only. Writes the full before / after snapshot to audit_trail_entries
         *     in the same transaction; if the audit write fails, the UPDATE rolls back.
         */
        patch: operations["patch_threshold_register_api_v1_admin_threshold_register__metric_id__patch"];
        trace?: never;
    };
    "/api/v1/audit/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Search
         * @description Search the audit trail with role-scoped row visibility.
         *
         *     Filters: actor_user_id, resource_type, resource_id, http_method, outcome,
         *     time_window. Cursor pagination on (occurred_at DESC, entry_id DESC).
         *
         *     Scope (per kickoff):
         *       - PO/AP=true       -> all rows
         *       - PO/AP=false      -> own actions only (actor_user_id = self)
         *       - DD/AP=true       -> all rows (programme scoping deferred)
         *       - FL/AP=true       -> all rows (programme scoping deferred)
         *       - DD/AP=false      -> 403 ApFlagDenied (audit row written)
         *       - FL/AP=false      -> 403 ApFlagDenied (audit row written)
         *       - PM, HRBP, RO     -> 403 RoleDenied (audit row written)
         */
        get: operations["get_audit_search_api_v1_audit_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/entry/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Entry Detail
         * @description Return one audit row including before / after JSON and diff.
         *
         *     Strict AP: every allowed role must have ap_flag=true; PortfolioOwner
         *     with AP=false is denied with ApFlagDenied (no own-actions carve-out
         *     here because there is no metadata-only fallback).
         *
         *     diff is the shallow top-level delta between before_json and after_json;
         *     null when either side is null.
         *
         *     Reads are not audited on success per D-039 ruling 8; denial paths
         *     (RoleDenied, ApFlagDenied) are audited by require_audit_access.
         *     404 is returned for an unknown entry_id with no audit row.
         */
        get: operations["get_audit_entry_detail_api_v1_audit_entry__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programmes/{code}/raids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programme Raids */
        get: operations["list_programme_raids_api_v1_programmes__code__raids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programmes/{code}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programme Milestones */
        get: operations["list_programme_milestones_api_v1_programmes__code__milestones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programmes/{code}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programme Health */
        get: operations["list_programme_health_api_v1_programmes__code__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditEntryDetail
         * @description Full audit entry including before / after JSON and server-computed diff.
         *
         *     Returned by GET /api/v1/audit/entry/{entry_id}. The endpoint is gated
         *     on AP=true regardless of role (require_audit_access strict_ap=True).
         *     diff is null when either before_json or after_json is null.
         */
        AuditEntryDetail: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Actor User Id
             * Format: uuid
             */
            actor_user_id: string;
            /** Actor Role */
            actor_role: string;
            /** Http Method */
            http_method: string;
            /** Endpoint */
            endpoint: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string | null;
            /** Outcome */
            outcome: string;
            /** Ip Address */
            ip_address: string | null;
            /** Before Json */
            before_json: Record<string, never> | null;
            /** After Json */
            after_json: Record<string, never> | null;
            diff: components["schemas"]["AuditEntryDiff"] | null;
        };
        /**
         * AuditEntryDiff
         * @description Shallow top-level diff between before_json and after_json.
         *
         *     Slice 5c implementation: top-level keys only. Deep diff (nested object
         *     paths, array index alignment) is a future enhancement. Each section
         *     is keyed by the field name; values mirror the original JSON shape.
         */
        AuditEntryDiff: {
            /**
             * Added
             * @description Keys present in after_json but not in before_json.
             */
            added?: Record<string, never>;
            /**
             * Removed
             * @description Keys present in before_json but not in after_json.
             */
            removed?: Record<string, never>;
            /**
             * Changed
             * @description Keys present in both with different values. Each entry is {'before': <prior>, 'after': <new>}.
             */
            changed?: {
                [key: string]: Record<string, never>;
            };
        };
        /**
         * AuditSearchEntry
         * @description One row in a search response. Carries metadata only; before / after
         *     JSON are not included in search results to keep the response small and
         *     so non-AP callers cannot indirectly read mutation deltas.
         */
        AuditSearchEntry: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /**
             * Actor User Id
             * Format: uuid
             */
            actor_user_id: string;
            /** Actor Role */
            actor_role: string;
            /** Endpoint */
            endpoint: string;
            /** Http Method */
            http_method: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Outcome */
            outcome: string;
            /** Resource Type */
            resource_type: string;
            /** Resource Id */
            resource_id: string | null;
            /** Ip Address */
            ip_address: string | null;
            /** User Agent */
            user_agent: string | null;
        };
        /**
         * AuditSearchResponse
         * @description Wrapped list response. Mirrors the slice 3 list response convention
         *     (TierConfigList, ThresholdRegisterList) plus pagination cursor and
         *     total_count for the unwrapped underlying query.
         */
        AuditSearchResponse: {
            /** Items */
            items: components["schemas"]["AuditSearchEntry"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null when no more results. Pass back as ?cursor=... to continue.
             */
            next_cursor?: string | null;
            /**
             * Total Count
             * @description Total rows matching the filters (unrelated to page size).
             */
            total_count: number;
            /** Page Size */
            page_size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthListResponse */
        HealthListResponse: {
            /** Items */
            items: components["schemas"]["HealthSnapshotItem"][];
            /** Count */
            count: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** HealthSnapshotItem */
        HealthSnapshotItem: {
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Programme Code */
            programme_code: string;
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /**
             * Overall Rag
             * @enum {string}
             */
            overall_rag: "Red" | "Amber" | "Green" | "Watching" | "Failing";
            /** Schedule Rag */
            schedule_rag: ("Red" | "Amber" | "Green" | "Watching" | "Failing") | null;
            /** Budget Rag */
            budget_rag: ("Red" | "Amber" | "Green" | "Watching" | "Failing") | null;
            /** Resources Rag */
            resources_rag: ("Red" | "Amber" | "Green" | "Watching" | "Failing") | null;
            /** Risks Rag */
            risks_rag: ("Red" | "Amber" | "Green" | "Watching" | "Failing") | null;
            /** Commentary */
            commentary: string | null;
            /**
             * Captured By User Id
             * Format: uuid
             */
            captured_by_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LoginRequest
         * @description Body for POST /api/v1/auth/login. extra='forbid' rejects unknown keys
         *     so a forwarded `password_hash` or `role` never leaks through the boundary.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Issued JWT plus minimal user metadata. password_hash is never returned;
         *     no log line emits the request password or the issued token.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Role */
            role: string;
            /** Ap Flag */
            ap_flag: boolean;
        };
        /** MilestoneItem */
        MilestoneItem: {
            /**
             * Milestone Id
             * Format: uuid
             */
            milestone_id: string;
            /** Programme Code */
            programme_code: string;
            /** Title */
            title: string;
            /** Baseline Date */
            baseline_date: string | null;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "On Track" | "At Risk" | "Delayed" | "Complete";
            /** Completion Pct */
            completion_pct: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MilestoneListResponse */
        MilestoneListResponse: {
            /** Items */
            items: components["schemas"]["MilestoneItem"][];
            /** Count */
            count: number;
        };
        /** RAIDItem */
        RAIDItem: {
            /**
             * Raid Id
             * Format: uuid
             */
            raid_id: string;
            /** Programme Code */
            programme_code: string;
            /**
             * Raid Type
             * @enum {string}
             */
            raid_type: "Risk" | "Assumption" | "Issue" | "Dependency";
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "Critical" | "High" | "Medium" | "Low";
            /**
             * Status
             * @enum {string}
             */
            status: "Open" | "Escalated" | "Mitigated" | "Accepted" | "Closed";
            /** Owner User Id */
            owner_user_id: string | null;
            /** Mitigation Date */
            mitigation_date: string | null;
            /**
             * Raised Date
             * Format: date
             */
            raised_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RAIDListResponse */
        RAIDListResponse: {
            /** Items */
            items: components["schemas"]["RAIDItem"][];
            /** Count */
            count: number;
        };
        /**
         * ThresholdRegisterList
         * @description GET /api/v1/admin/threshold-register response.
         */
        ThresholdRegisterList: {
            /** Items */
            items: components["schemas"]["ThresholdRegisterResponse"][];
        };
        /** ThresholdRegisterResponse */
        ThresholdRegisterResponse: {
            /** Metric Id */
            metric_id: string;
            /** Display Name */
            display_name: string;
            /** Direction */
            direction: string;
            /** Green Threshold */
            green_threshold: string;
            /** Amber Threshold */
            amber_threshold: string;
            /** Red Threshold */
            red_threshold: string;
            /** Range Lower */
            range_lower: string | null;
            /** Range Upper */
            range_upper: string | null;
            /** Rationale Text */
            rationale_text: string;
            /**
             * Last Calibrated At
             * Format: date-time
             */
            last_calibrated_at: string;
            /**
             * Last Calibrated By
             * Format: uuid
             */
            last_calibrated_by: string;
            /** Owning Role */
            owning_role: string;
        };
        /**
         * ThresholdRegisterUpdate
         * @description Body for PATCH /api/v1/admin/threshold-register/{metric_id}.
         *
         *     All fields optional; at least one must be provided. extra='forbid'
         *     rejects unknown keys. Setting range_lower / range_upper to null in
         *     the request body is treated as "no change" in this slice; emptying
         *     those fields requires a separate slice when needed (see slice 2 hand-back).
         *
         *     metric_id is the URL path param and not editable. last_calibrated_at
         *     and last_calibrated_by are system-set on every PATCH.
         */
        ThresholdRegisterUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Direction */
            direction?: string | null;
            /** Green Threshold */
            green_threshold?: number | string | null;
            /** Amber Threshold */
            amber_threshold?: number | string | null;
            /** Red Threshold */
            red_threshold?: number | string | null;
            /** Range Lower */
            range_lower?: number | string | null;
            /** Range Upper */
            range_upper?: number | string | null;
            /** Rationale Text */
            rationale_text?: string | null;
            /** Owning Role */
            owning_role?: string | null;
        };
        /**
         * TierConfigList
         * @description GET /api/v1/admin/tier-config response. Wrapped list for forward
         *     extensibility (pagination, total_count when row counts grow).
         */
        TierConfigList: {
            /** Items */
            items: components["schemas"]["TierConfigResponse"][];
        };
        /** TierConfigResponse */
        TierConfigResponse: {
            /** Tier Number */
            tier_number: number;
            /** Default Label */
            default_label: string;
            /** Display Label */
            display_label: string;
            /** Description Text */
            description_text: string | null;
            /** Sla Hint Hours */
            sla_hint_hours: number | null;
            /** Role Mapping */
            role_mapping: Record<string, never>;
            /** Active */
            active: boolean;
            /**
             * Last Edited At
             * Format: date-time
             */
            last_edited_at: string;
            /**
             * Last Edited By User Id
             * Format: uuid
             */
            last_edited_by_user_id: string;
        };
        /**
         * TierConfigUpdate
         * @description Body for PATCH /api/v1/admin/tier-config/{tier_number}.
         *
         *     All fields optional; at least one must be provided. extra='forbid'
         *     rejects unknown keys so contract drift is caught at the boundary.
         */
        TierConfigUpdate: {
            /** Display Label */
            display_label?: string | null;
            /** Description Text */
            description_text?: string | null;
            /** Active */
            active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tier_config_api_v1_admin_tier_config__tier_number__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TierConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tier_config_list_api_v1_admin_tier_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierConfigList"];
                };
            };
        };
    };
    get_threshold_register_list_api_v1_admin_threshold_register_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdRegisterList"];
                };
            };
        };
    };
    patch_threshold_register_api_v1_admin_threshold_register__metric_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdRegisterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_search_api_v1_audit_search_get: {
        parameters: {
            query?: {
                actor_user_id?: string | null;
                resource_type?: string | null;
                resource_id?: string | null;
                http_method?: string | null;
                outcome?: string | null;
                time_window?: string | null;
                cursor?: string | null;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_entry_detail_api_v1_audit_entry__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_programme_raids_api_v1_programmes__code__raids_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Programme code, e.g. PEGASUS */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RAIDListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_programme_milestones_api_v1_programmes__code__milestones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Programme code, e.g. PEGASUS */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilestoneListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_programme_health_api_v1_programmes__code__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Programme code, e.g. PEGASUS */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
